# Site settings
title: 左岸小贼的博客
email: gonewbee@sina.com
description: > # this means to ignore newlines until "baseurl:"
  使用jekyll搭建的博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gonewbee.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gonewbee

# Build settings
markdown: kramdown
kramdown:
	input: GFM
